openapi: "3.0.2"
info:
  title: API Wisata
  description: Dokumentasi API Wisata Matkul Rekayasa Web
  version: '1.0'
  termsOfService: http://swagger.io/terms/
contact:
  email: sherinkuy@gmail.com
License:
name: Apache 2.0
url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080/json/server
tags:
paths: